# Generated by Django 5.2.7 on 2025-11-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_create", "Can create a new book"),
                    ("can_change", "Can change an existing book"),
                    ("can_delete", "Can delete a book"),
                    ("can_view", "Can view book details"),
                ]
            },
        ),
    ]
