# Generated by Django 5.2.7 on 2025-11-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="published_date",
            new_name="publication_year",
        ),
    ]
