# Generated by Django 5.2.7 on 2025-11-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the book", max_length=200),
                ),
                (
                    "author",
                    models.CharField(help_text="The author's name", max_length=100),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="13-digit ISBN number",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "published_date",
                    models.DateField(help_text="The date when the book was published"),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of pages in the book"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price of the book",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief description of the book"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the book is available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at", "title"],
            },
        ),
    ]
